# $Id: freebsd-doc.pod 14 2016-07-12 19:12:56Z mark $
# $URL: file:///D:/svn/J70267938-Dev-Proj-File/trnk/src/license/freebsd-doc.pod $

=head1 Copyright

(c) Copyright 2016 Mark J. Jensen

=head1 The FreeBSD Documentation License

Redistribution and use in source
(Impress, Powerpoint, Writer, Word, ...) and
'compiled' forms
(SGML, HTML, PDF, PostScript, RTF and so forth)
with or without modification,
are permitted provided that the following conditions are met:

Redistributions of source code
(Impress, Powerpoint, Writer, Word, ...)
must retain the above copyright notice,
this list of conditions and
the following disclaimer as the first lines of this file unmodified.

Redistributions in compiled form
(transformed to other DTDs, converted to PDF, PostScript, RTF and other formats)
must reproduce the above copyright notice,
this list of conditions and
the following disclaimer in the documentation and/or
other materials provided with the distribution.

THIS DOCUMENTATION IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS
"AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
INCLUDING,
BUT NOT LIMITED TO,
THE IMPLIED WARRANTIES OF MERCHANTABILITY AND
FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE FREEBSD DOCUMENTATION PROJECT
BE LIABLE
FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR
TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
ARISING IN ANY WAY OUT OF THE USE OF THIS DOCUMENTATION,
EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

=cut
